### ISSUE TITLE
[UserStory] As a user, I want to view a roadmap of my degree so that I know which classes I should take.

### ISSUE THREAD

**Issue by maingockien01** [maingockien01/comp4350-team8#7]
# Scenario: 
```
Given I'm on Roadmap page,
When I click "View degree roadmap",
and select a degree,
Then web will show me a recommended course roadmap for the degree.
```
# Tasks
## Frontend
- [x] roadmap component (to be designed): a list of courses in tree structure view
- [x] Degree selection dropbox
## Backend 
- [x] Return the list of courses for the roadmap associated with the degree.
- [x] Return the list of available degrees 
### Degrees
- [x] Request: `GET degrees`
- [x] Response: 
```
{
  degrees: [{
    name: string,
    id: number,
  },...]
}
```
### Roadmap
- [x] Request: `GET roadmaps?degree_id={int}`
- [x] Backend Response: 
```
{
  courses: [{
    name: string,
    major: string,
    course_number: string,
  },...],
}
```

# Sequence diagram

![UserStory_7_Realone](https://github.com/maingockien01/comp4350-team8/assets/40449746/87ad3ce3-5616-42f6-9095-4b084e6a4a3d)
