### ISSUE TITLE
[UserStory] As a user, I want to create my own customized roadmap.

### ISSUE THREAD

**Issue by maingockien01** [maingockien01/comp4350-team8#8]
# Scenario:
```
given I'm a logged-in user,
and on Roadmap page,
when I click see my roadmap,
then web will show me my course roadmap,
and I could add and remove courses in roadmap.
when I click "View degree roadmap",
and select a degree,
then web will show option to copy/overwrite my customized roadmap as a template.
```

# Tasks

## Frontend
- [ ] Roadmap component
- [ ] Copy roadmap button
- [ ] Add/Delete courses section
- [ ] Export/Import button and interactions

## Backend
- [ ] Store a roadmap for each user
  - [ ] Empty
  - [ ] From existing roadmap
- [ ] CRUD roadmap courses
- [ ] Export/Import roadmap

## API
- [ ] `GET my/roadmap`
- [ ] `POST my/roadmap`
- [ ] `PUT my/roadmap/:id`
- [ ] `POST my/roadmap/courses?course_id=`
- [ ] `DELETE my/roadmap/courses?course_id=`
- [ ] `GET my/roadmap/export`
- [ ] `POST my/roadmap/import`

# Sequence Diagram
![UserStory_7](https://github.com/maingockien01/comp4350-team8/assets/40449746/3cb103ab-9397-4cbd-9f35-12df131e02b2)
